//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_work
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservations
    {
        public int reservation_id { get; set; }
        public int user_id { get; set; }
        public int room_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int price { get; set; }
        public int total { get; set; }
    
        public virtual rooms rooms { get; set; }
        public virtual users users { get; set; }
    }
}
